server:
  port: 8080
  servlet:
    context-path: /atomikos

spring:
  profiles:
    include: dev
  application:
    name: atomikos

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


